export default function TermsOfService() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16 text-gray-800">
      <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-10">Last updated: May 2026</p>

      <p className="mb-6">
        Welcome to <strong>TTA – Text to Audio</strong>. By accessing or using our platform at{" "}
        <a href="https://tta-text-to-audio.vercel.app" className="text-blue-600 underline">
          https://tta-text-to-audio.vercel.app
        </a>
        , you agree to be bound by these Terms of Service ("Terms"). Please read them carefully
        before using TTA.
      </p>

      {/* Section 1 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">1. Acceptance of Terms</h2>
      <p className="mb-4">
        By using TTA, you confirm that you are at least 13 years of age and agree to these
        Terms. If you do not agree, please do not use the platform.
      </p>

      {/* Section 2 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">2. Description of Service</h2>
      <p className="mb-4">
        TTA is an AI-powered text-to-audio generation platform that converts written text into
        audio files using voice synthesis technology. The service is currently offered free of
        charge and is accessible via web browser.
      </p>

      {/* Section 3 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">3. Acceptable Use</h2>
      <p className="mb-4">You agree to use TTA only for lawful purposes. You must NOT use TTA to:</p>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>Generate audio containing hate speech, threats, or discriminatory content</li>
        <li>Create defamatory, harassing, or abusive content targeting individuals</li>
        <li>Produce audio intended to deceive, defraud, or impersonate others</li>
        <li>Generate content that violates the intellectual property rights of others</li>
        <li>Distribute spam, malware, or any harmful content</li>
        <li>Use the service for any illegal activity under applicable law</li>
        <li>Attempt to reverse-engineer, scrape, or overload our systems</li>
      </ul>
      <p className="mb-4">
        We reserve the right to suspend or terminate access for any user who violates these rules.
      </p>

      {/* Section 4 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">4. Intellectual Property</h2>

      <h3 className="text-lg font-semibold mt-6 mb-2">a) Your Content</h3>
      <p className="mb-4">
        You retain ownership of the text you submit to TTA. By submitting text, you grant us a
        limited, temporary license to process it solely for the purpose of generating your audio
        output.
      </p>

      <h3 className="text-lg font-semibold mt-6 mb-2">b) Generated Audio</h3>
      <p className="mb-4">
        The audio generated by TTA based on your input is provided for your personal and
        commercial use. However, you are solely responsible for ensuring your use of the
        generated audio does not infringe on any third-party rights.
      </p>

      <h3 className="text-lg font-semibold mt-6 mb-2">c) TTA Platform</h3>
      <p className="mb-4">
        All code, design, branding, and content of the TTA platform is the intellectual property
        of Shivang Bijalwan. You may not copy, modify, or distribute any part of TTA without
        explicit written permission.
      </p>

      {/* Section 5 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">5. Disclaimer of Warranties</h2>
      <p className="mb-4">
        TTA is provided <strong>"as is"</strong> and <strong>"as available"</strong> without
        warranties of any kind, either express or implied. We do not guarantee that:
      </p>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>The service will be uninterrupted or error-free</li>
        <li>The audio output will meet your specific requirements</li>
        <li>Any errors or bugs will be corrected within a specific timeframe</li>
      </ul>

      {/* Section 6 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">6. Limitation of Liability</h2>
      <p className="mb-4">
        To the fullest extent permitted by law, TTA and its creator shall not be liable for any
        indirect, incidental, special, consequential, or punitive damages arising from your use
        of — or inability to use — the platform, including but not limited to loss of data,
        revenue, or reputation.
      </p>

      {/* Section 7 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">7. Third-Party Services</h2>
      <p className="mb-4">
        TTA relies on third-party infrastructure including Vercel for hosting and AI providers
        for voice synthesis. We are not responsible for the availability, accuracy, or policies
        of these third-party services.
      </p>

      {/* Section 8 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">8. Modifications to the Service</h2>
      <p className="mb-4">
        We reserve the right to modify, suspend, or discontinue TTA (or any part of it) at any
        time, with or without notice. We are not liable to you or any third party for any such
        changes.
      </p>

      {/* Section 9 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">9. Changes to These Terms</h2>
      <p className="mb-4">
        We may update these Terms from time to time. The updated version will be posted on this
        page with a new "Last updated" date. Continued use of TTA after changes constitutes your
        acceptance of the revised Terms.
      </p>

      {/* Section 10 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">10. Governing Law</h2>
      <p className="mb-4">
        These Terms are governed by and construed in accordance with the laws of India. Any
        disputes arising from these Terms shall be subject to the jurisdiction of the courts
        located in Uttarakhand, India.
      </p>

      {/* Section 11 */}
      <h2 className="text-2xl font-semibold mt-10 mb-3">11. Contact Us</h2>
      <p className="mb-4">
        If you have any questions about these Terms, please reach out:
      </p>
      <ul className="list-none pl-0 mb-4 space-y-1">
        <li>
          <strong>Creator:</strong> Shivang Bijalwan
        </li>
        <li>
          <strong>Website:</strong>{" "}
          <a href="https://shivang-website.vercel.app/" className="text-blue-600 underline">
            https://shivang-website.vercel.app/
          </a>
        </li>
      </ul>

      <hr className="my-10 border-gray-200" />
      <p className="text-sm text-gray-400 text-center">
        © {new Date().getFullYear()} TTA – Text to Audio. All rights reserved.
      </p>
    </main>
  );
}